id: A782A04F0
title: A Prayer of Aspiration for the Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:20:32.668034
  last_modified_at: 2022-03-01 03:20:32.668037
