id: A782A04F0
title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
  Mountain of Glory'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:20:32.664484
  last_modified_at: 2022-03-01 03:20:32.664492
