id: A782A04F0
title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
  Mountain of Glory
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:20:32.671885
  last_modified_at: 2022-03-01 03:20:32.671888
