id: A782A04F0
title: Threefold Aspiration for Rebirth in Zangdok Palri
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:20:32.676840
  last_modified_at: 2022-03-01 03:20:32.676843
